-- liquibase formatted sql

-- changeset abzal:1
CREATE TABLE IF NOT EXISTS BRANDS
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR NOT NULL,
    DESCRIPTION VARCHAR
);

-- changeset abzal:2
CREATE TABLE IF NOT EXISTS COUNTRIES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    CODE VARCHAR NOT NULL UNIQUE
);

-- changeset abzal:3
CREATE TABLE IF NOT EXISTS CARS
(
    ID         BIGSERIAL PRIMARY KEY,
    BRAND_ID   BIGINT,
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (ID),
    MODEL      VARCHAR UNIQUE,
    PRICE      DOUBLE PRECISION,
    VOLUME     DOUBLE PRECISION,
    COUNTRY_ID BIGINT,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID)
);

-- changeset daniyar:4
CREATE TABLE IF NOT EXISTS USERS
(
    ID            BIGSERIAL PRIMARY KEY,
    EMAIL         VARCHAR NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR NOT NULL,
    FULL_NAME     VARCHAR,
    GENDER        VARCHAR
);

-- changeset nurlybek:5
CREATE TABLE IF NOT EXISTS NOTEBOOKS
(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR NOT NULL ,
    PRICE DOUBLE PRECISION NOT NULL ,
    MEMORY VARCHAR,
    RAM VARCHAR,
    OS VARCHAR,
    BRAND_ID BIGINT,
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);