-- liquibase formatted sql

-- changeset abzal:1
INSERT INTO COUNTRIES (NAME, CODE)
VALUES ('Afghanistan', 'AF'),
       ('Albania', 'AL'),
       ('Algeria', 'DZ'),
       ('Andorra', 'AD'),
       ('Angola', 'AO'),
       ('Antigua and Barbuda', 'AG'),
       ('Argentina', 'AR'),
       ('Armenia', 'AM'),
       ('Australia', 'AU'),
       ('Austria', 'AT'),
       ('Azerbaijan', 'AZ'),
       ('Bahamas', 'BS'),
       ('Bahrain', 'BH'),
       ('Bangladesh', 'BD'),
       ('Barbados', 'BB'),
       ('Belarus', 'BY'),
       ('Belgium', 'BE'),
       ('Belize', 'BZ'),
       ('Benin', 'BJ'),
       ('Bhutan', 'BT'),
       ('Bolivia (Plurinational State of)', 'BO'),
       ('Bosnia and Herzegovina', 'BA'),
       ('Botswana', 'BW'),
       ('Brazil', 'BR'),
       ('Brunei Darussalam', 'BN'),
       ('Bulgaria', 'BG'),
       ('Burkina Faso', 'BF'),
       ('Burundi', 'BI'),
       ('Cabo Verde', 'CV'),
       ('Cambodia', 'KH'),
       ('Cameroon', 'CM'),
       ('Canada', 'CA'),
       ('Central African Republic', 'CF'),
       ('Chad', 'TD'),
       ('Chile', 'CL'),
       ('China', 'CN'),
       ('Colombia', 'CO'),
       ('Comoros', 'KM'),
       ('Congo', 'CG'),
       ('Costa Rica', 'CR'),
       ('Croatia', 'HR'),
       ('Cuba', 'CU'),
       ('Cyprus', 'CY'),
       ('Czechia', 'CZ'),
       ('Democratic Republic of the Congo', 'CD'),
       ('Denmark', 'DK'),
       ('Djibouti', 'DJ'),
       ('Dominica', 'DM'),
       ('Dominican Republic', 'DO'),
       ('Ecuador', 'EC'),
       ('Egypt', 'EG'),
       ('El Salvador', 'SV'),
       ('Equatorial Guinea', 'GQ'),
       ('Eritrea', 'ER'),
       ('Estonia', 'EE'),
       ('Eswatini', 'SZ'),
       ('Ethiopia', 'ET'),
       ('Fiji', 'FJ'),
       ('Finland', 'FI'),
       ('France', 'FR'),
       ('Gabon', 'GA'),
       ('Gambia', 'GM'),
       ('Georgia', 'GE'),
       ('Germany', 'DE'),
       ('Ghana', 'GH'),
       ('Greece', 'GR'),
       ('Grenada', 'GD'),
       ('Guatemala', 'GT'),
       ('Guinea', 'GN'),
       ('Guinea‑Bissau', 'GW'),
       ('Guyana', 'GY'),
       ('Haiti', 'HT'),
       ('Honduras', 'HN'),
       ('Hungary', 'HU'),
       ('Iceland', 'IS'),
       ('India', 'IN'),
       ('Indonesia', 'ID'),
       ('Iran (Islamic Republic of)', 'IR'),
       ('Iraq', 'IQ'),
       ('Ireland', 'IE'),
       ('Israel', 'IL'),
       ('Italy', 'IT'),
       ('Jamaica', 'JM'),
       ('Japan', 'JP'),
       ('Jordan', 'JO'),
       ('Kazakhstan', 'KZ'),
       ('Kenya', 'KE'),
       ('Kiribati', 'KI'),
       ('Kuwait', 'KW'),
       ('Kyrgyzstan', 'KG'),
       ('Lao People’s Democratic Republic', 'LA'),
       ('Latvia', 'LV'),
       ('Lebanon', 'LB'),
       ('Lesotho', 'LS'),
       ('Liberia', 'LR'),
       ('Libya', 'LY');
